In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl
import scanpy.api as sc

sc.settings.verbosity = 1  # verbosity: errors (0), warnings (1), info (2), hints (3)
sc.settings.set_figure_params(dpi=80)  # low dpi (dots per inch) yields small inline figures
sc.logging.print_versions()
results_file = './write/zheng17.h5ad'

scanpy==1.3.2 anndata==0.6.11 numpy==1.14.6 scipy==1.1.0 pandas==0.23.4 scikit-learn==0.19.2 statsmodels==0.9.0 


In [1]:
from scipy import sparse, io

m = sparse.csr_matrix([[0,0,0],[1,0,0],[0,1,0]])
m              # <3x3 sparse matrix of type '<type 'numpy.int64'>' with 2 stored elements in Compressed Sparse Row format>

<3x3 sparse matrix of type '<class 'numpy.int32'>'
	with 2 stored elements in Compressed Sparse Row format>

In [2]:
io.mmwrite("data/test.mtx", m)
del m

In [3]:
newm = io.mmread("data/test.mtx")

In [5]:
newm.todense()

matrix([[0, 0, 0],
        [1, 0, 0],
        [0, 1, 0]], dtype=int64)

In [38]:
from anndata import AnnData
import numpy as np
import scanpy.api as sc
adata = AnnData(np.array([[1, 0], [3, 0], [1,2]]))
print(adata.obs)


Empty DataFrame
Columns: []
Index: [0, 1, 2]


In [28]:
 print(adata.X.sum(axis=1))

[1. 3. 3.]


In [29]:
sc.pp.normalize_per_cell(adata, counts_per_cell_after=100)
print(adata.obs)
adata.X

   n_counts
0       1.0
1       3.0
2       3.0


array([[100.      ,   0.      ],
       [100.      ,   0.      ],
       [ 33.333336,  66.66667 ]], dtype=float32)

In [30]:
print(adata.X.sum(axis=1))

[100.      100.      100.00001]


In [31]:
sc.pp.normalize_per_cell(adata, counts_per_cell_after=1,key_n_counts='n_counts2')
print(adata.obs)
print(adata.X.sum(axis=1))

   n_counts   n_counts2
0       1.0  100.000000
1       3.0  100.000000
2       3.0  100.000008
[1. 1. 1.]


In [34]:
adata.var['xxx'] = adata.X.mean(axis=0)

In [35]:
adata.var

xxx
0  0.777778
1  0.222222